# Generated by Django 2.2.7 on 2020-03-02 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keyentry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdaily2',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formhourly',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formmonthly',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='cloudheightunits',
            field=models.CharField(blank=True, choices=[('feet', 'feet'), ('metres', 'metres')], db_column='cloudHeightUnits', default='feet', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag01',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag02',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag03',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag04',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag05',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag06',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag07',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag08',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag09',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag10',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag11',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag12',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag13',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag14',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag15',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag16',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag17',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag18',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag19',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag20',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag21',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag22',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag23',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag24',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag25',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag26',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag27',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag28',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag29',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag30',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='flag31',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='precipunits',
            field=models.CharField(blank=True, choices=[('mm', 'mm'), ('inches', 'inches')], db_column='precipUnits', default='mm', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='temperatureunits',
            field=models.CharField(blank=True, choices=[('Deg C', 'Deg C'), ('Deg F', 'Deg F')], db_column='temperatureUnits', default='Deg C', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='formdaily2',
            name='visunits',
            field=models.CharField(blank=True, choices=[('metres', 'metres'), ('yards', 'yards')], db_column='visUnits', default='metres', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag00',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag01',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag02',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag03',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag04',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag05',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag06',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag07',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag08',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag09',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag10',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag11',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag12',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag13',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag14',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag15',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag16',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag17',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag18',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag19',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag20',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag21',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag22',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formhourly',
            name='flag23',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag01',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag02',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag03',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag04',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag05',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag06',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag07',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag08',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag09',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag10',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag11',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='formmonthly',
            name='flag12',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('T', 'T'), ('E', 'E'), ('G', 'G'), ('D', 'D')], max_length=255, null=True),
        ),
    ]
