# Generated by Django 2.2.7 on 2020-03-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyentry', '0002_auto_20200302_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formmonthly',
            name='mm_04',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
